baseURL: "https://yaelgrosjean.com"
languageCode : 'fr-FR'
defaultContentLanguage : "fr"
defaultContentLang : "fr"
languageName: Français
title: "Yaël Grosjean"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Yaël Grosjean"
  description: Je vous présente mon portfolio en ligne
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Yaël Grosjean" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Bonjour, je m'appelle"
    title: "Yaël."
    subtitle: "Dans l'informatique depuis 10 ans"
    content: "Je suis un développeur d'applications passionné. J'ai tendance à utiliser les dernières technologies pour construire des solutions qui ont une belle apparence, sont agréables à utiliser et fonctionnent correctement."
    image: /images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/YaelGj
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/yael-grosjean/
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "Qui suis-je ?"
    image: "/images/me.png"
    content: |-
      Je suis 

      Je travaille actuellement en tant que chef de projet / développeur d'application PowerApps-DataVerse pour la SNCF.
    skills:
      enable: true
      title: "Voici les dernières technologies avec lesquelles j'ai travaillé:"
      items:
        - "PowerApps"
        - "DataVerse"
        - "Hugo"
        - "Python"
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Chef de projet / Développeur"
        company: "SNCF"
        companyUrl: "https://www.sncf-voyageurs.com/fr/"
        date: "Sept 2020 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "-	Réalisation de cahiers des charges en étroite collaboration avec les parties prenantes, afin d'assurer le succès du projet. Implémentation de solutions intégrées sur la plateforme PowerPlatform (WebApp & Mobile) basée sur Dataverse, l’écosystème Cloud de Microsoft.
          -	Gestion complète du cycle de développement des applications dédiées à la gestion des congés de disponibilité, du recrutement des alternants, ainsi que de la déclaration et de la gestion des arrêts de travail.
          -	Dispensation de formations à l'intention des utilisateurs finaux, avec une envergure pouvant atteindre plus de 200 participants par session.
          -	Continuelle amélioration et maintenance des applications associées à la gestion des arrêts de travail, des accidents de travail, des mouvements de personnel, du suivi des temps partiels, des gratifications exceptionnelles, des sorties de production, du télétravail, des congés pour soins familiaux, ainsi que de la génération automatisée d'attestations employeurs pour les situations de crise telles que la COVID-19 et la pollution.
          -	Supervision et encadrement de deux stagiaires pour garantir une progression optimale dans l'exécution de leurs missions respectives."

      - job: "Administrateur système"
        company: "VoxPro - Airbnb - Google"
        companyUrl: "https://www.linkedin.com/company/voxpro/"
        date: "Jan 2020 - Avr 2020"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: false
          content: Collaboration au sein d’une équipe anglophone et internationale, assistance utilisateurs, installation de nouveaux open-space, management des nouveaux stagiaires.
        content: |
          -	Participation proactive au sein d'une équipe dynamique et multiculturelle, dédiée à l'excellence opérationnelle. Responsabilité de la fourniture d'une assistance informatique de premier ordre aux utilisateurs et mise en place de solutions informatiques innovantes pour les nouveaux espaces de travail. Déploiement et supervision de trois stagiaires talentueux, venant d'horizons internationaux, dans le but d'optimiser leur potentiel et d'assurer l'alignement stratégique.

      - job: "Administrateur Systèmes et réseaux"
        company: "Sacred"
        companyUrl: "https://www.sacredgroup.com/fr/corporate/index.php "
        date: "Sept 2017 - Sept 2019"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Assistance des utili
          - Gestion du projet de déploiement WIFI en milieu industrielle afin d’intégrer le relever de production automatiquement à l’aide d’un chariot autonome de reporting sur batterie.
          - Création d’une interface graphique d’administration distante en PowerShell.

      - job: "Technicien SAV et réparation de drone"
        company: "studioSPORT"
        companyUrl: "https://www.studiosport.fr/"
        date: "Mai 2017 - Sept 2017"
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          J'ai eu la chance de faire parti de l'équipe service après vente de studioSPORT.

          - Réparation de Drones de prise de vue aérienne civile, professionnel et de course.
          - Assistance client.

      - job: "Barman - Serveur"
        company: "Restaurants"
        companyUrl: "https://www.aubureau.fr/"
        date: "Feb 2016 - Mai 2017"
        content: "Serveur et barman dans divers bar et restaurants de Rouen."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "CHEF DE PROJET INGÉNIERIE LOGICIELLE"
        school:
          name: "IPI Lyon, groupe IGS"
          url: "https://www.ipi-ecoles.com/"
        date: "2021 - 2023"
        content: |-
          Diplôme RNCP de niveau bac+5
            - CONCEPTION ET DÉVELOPPEMENT LOGICIEL
            - Conception objet UML
            - Maîtriser l’analyse et le développement logiciel JAVA
            - Principes de programmation de langages intégrés (Environnement .NET)
            - Algorithme
            - Programmation et conception en environnement intégré JavaScript (Angular en front-end et Node.JS en back-end)
            - ADMINISTRATION BASES DE DONNÉES
            - Méthode merise
            - SQL
            - Conception de Bases de données
            - Outils de gestion SGBDR
            - GESTION DE PROJETS
            - MANAGEMENT DU CHANGEMENT
            - AUDIT ET ÉVALUATION DES SI
            - RECONFIGURATION DE PROCESSUS, RÉINGÉNIERIE
            - URBANISATION ET SCHÉMA DIRECTEUR
            - DÉMARCHE QUALITÉ
            - PRATIQUE DE LA GESTION POUR NON-GESTIONNAIRES
            - COMMUNICATION – INFORMATION
            - DROIT ET TECHNOLOGIES DE L’INFORMATION
      - title: "Bachelor en ingénieurie logiciel"
        school:
          name: "Isitech Lyon"
          url: "https://www.ecole-isitech.com/"
        date: "2021 - 2023"
        content: |-
          Diplôme RNCP de niveau bac+3
            - Responsable de projet informatique en alternance.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
