baseURL: "https://yaelgrosjean.com"
languageCode : 'fr-FR'
defaultContentLanguage : "fr"
defaultContentLang : "fr"
languageName: Français
title: "Yaël Grosjean"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
googleAnalytics: G-VQSHDX7RM6

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Yaël Grosjean"
  description: Je vous présente mon portfolio en ligne
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Yaël Grosjean" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Bonjour, je m'appelle"
    title: "Yaël."
    subtitle: "Chef de projet et développeur freelance avec 10 ans d'expérience, je transforme les concepts en réalité numérique avec expertise et créativité."
    content: "Architecte d'application, Chef de projet, développeur, Formateur, Accompagnateur au changement, peu importe votre projet, je saurai vous accompagner dans vos problématiques informatiques"
    image: /images/PhotoYael.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/YaelGj
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/yael-grosjean/
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "Qui suis-je ?"
    image: "/images/me.png"
    content: |-
      Chef de projet et développeur freelance expérimenté, je transforme les idées en solutions numériques innovantes. Passionné par l'informatique, je m'engage à créer des applications et des sites web exceptionnels, combinant expertise technique et créativité pour atteindre vos objectifs avec succès.
    skills:
      enable: true
      title: "Voici les dernières technologies avec lesquelles j'ai travaillé:"
      items:
        - "PowerApps"
        - "DataVerse"
        - "Hugo"
        - "Python"
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Chef de projet / Développeur"
        company: "SNCF"
        companyUrl: "https://www.sncf-voyageurs.com/fr/"
        date: "Sept 2020 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: |
          -	Réalisation de cahiers des charges en étroite collaboration avec les parties prenantes, afin d'assurer le succès du projet. Implémentation de solutions intégrées sur la plateforme PowerPlatform (WebApp & Mobile) basée sur Dataverse, l’écosystème Cloud de Microsoft.
          -	Gestion complète du cycle de développement des applications dédiées à la gestion des congés de disponibilité, du recrutement des alternants, ainsi que de la déclaration et de la gestion des arrêts de travail.
          -	Dispensation de formations à l'intention des utilisateurs finaux, avec une envergure pouvant atteindre plus de 200 participants par session.
          -	Continuelle amélioration et maintenance des applications associées à la gestion des arrêts de travail, des accidents de travail, des mouvements de personnel, du suivi des temps partiels, des gratifications exceptionnelles, des sorties de production, du télétravail, des congés pour soins familiaux, ainsi que de la génération automatisée d'attestations employeurs pour les situations de crise telles que la COVID-19 et la pollution.
          -	Supervision et encadrement de deux stagiaires pour garantir une progression optimale dans l'exécution de leurs missions respectives.

      - job: "Administrateur système"
        company: "VoxPro - Airbnb - Google"
        companyUrl: "https://www.linkedin.com/company/voxpro/"
        date: "Jan 2020 - Avr 2020"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: false
          content: Collaboration au sein d’une équipe anglophone et internationale, assistance utilisateurs anglophones, installation de nouveaux open-space, management des nouveaux stagiaires.
        content: |
          -	Participation proactive au sein d'une équipe dynamique et multiculturelle, dédiée à l'excellence opérationnelle.
          - Responsabilité de la fourniture d'une assistance informatique de premier ordre aux utilisateurs et mise en place de solutions informatiques innovantes pour les nouveaux espaces de travail.
          - Déploiement et supervision de trois stagiaires anglophones, venant d'horizons internationaux, dans le but d'optimiser leur potentiel et d'assurer l'alignement stratégique.
          - Assistance utilisateurs anglophones.

      - job: "Administrateur Systèmes et réseaux"
        company: "Sacred"
        companyUrl: "https://www.sacredgroup.com/fr/corporate/index.php "
        date: "Sept 2017 - Sept 2019"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Assistance aux utilisateurs.
          - Gestion des systèmes de l'entreprise.
          - Gestion du projet de déploiement WIFI en milieu industrielle afin d’intégrer le relever de production automatiquement à l’aide d’un chariot autonome de reporting sur batterie.
          - Création d’une interface graphique d’administration distante en PowerShell.

      - job: "Technicien SAV et réparation de drone"
        company: "studioSPORT"
        companyUrl: "https://www.studiosport.fr/"
        date: "Mai 2017 - Sept 2017"
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          - Réparation de Drones de prise de vue aérienne civile, professionnel et de course.
          - Assistance client.

      - job: "Barman - Serveur"
        company: "Restaurants"
        companyUrl: "https://www.aubureau.fr/"
        date: "Feb 2016 - Mai 2017"
        content: "Serveur et barman dans divers bar et restaurants de Rouen, dont le bureau."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "CHEF DE PROJET INGÉNIERIE LOGICIELLE"
        school:
          name: "IPI Lyon, groupe IGS"
          url: "https://www.ipi-ecoles.com/"
        date: "2020 - 2023"
        content: |-
          Diplôme RNCP de niveau bac+5
            - CONCEPTION ET DÉVELOPPEMENT LOGICIEL
            - Conception objet UML
            - Maîtriser l’analyse et le développement logiciel JAVA
            - Principes de programmation de langages intégrés (Environnement .NET)
            - Algorithme
            - Programmation et conception en environnement intégré JavaScript (Angular en front-end et Node.JS en back-end)
            - ADMINISTRATION BASES DE DONNÉES
            - Méthode merise
            - SQL
            - Conception de Bases de données
            - Outils de gestion SGBDR
            - GESTION DE PROJETS.
            - MANAGEMENT DU CHANGEMENT
            - AUDIT ET ÉVALUATION DES SI.
            - RECONFIGURATION DE PROCESSUS, RÉINGÉNIERIE.
            - URBANISATION ET SCHÉMA DIRECTEUR.
            - DÉMARCHE QUALITÉ.
            - PRATIQUE DE LA GESTION POUR NON-GESTIONNAIRES.
            - COMMUNICATION – INFORMATION.
            - DROIT ET TECHNOLOGIES DE L’INFORMATION.

      - title: "Bachelor en ingénieurie logiciel"
        school:
          name: "Isitech Lyon"
          url: "https://www.ecole-isitech.com/"
        date: "2019 - 2020"
        content: |-
          Diplôme RNCP de niveau bac+3
            Responsable de projet informatique en alternance.

            - Développement	Systèmes & Réseaux.
            - Programmation structurée : C ++	Windows Server : Architecture Client / Serveur.
            - Programmation web : React	Découvrir la cybersécurité.
            - Programmation événementielle : C#	Mettre en place du cloud computing.
            - Programmation réalité virtuelle : C# / Unity3D	LPI 102 – Linux gestion des réseaux / Administration avancée.
            - Programmation blockchain : Solidity	Virtualiser avec Docker.
            - Base de données Microsoft SQL Server / NoSQL MongoDB.
        featuredLink:
          enable: true
          name: "Lien fiche formation"
          url: "https://www.ecole-isitech.com/formations/rpi/"

      - title: "Bac +2"
        school:
          name: ""
          url: "https://rouen.cesi.fr/"
        date: "2016 - 2018"
        content: |-
          - Installer, configurer et assurer la maintenance des PC.
          - Assurer la gestion des sauvegardes et la maintenance des équipements réseaux.
          - Installer, configurer et administrer les serveurs de l’entreprise.
          - Mettre en place des nouveaux services réseaux.
          - Assurer la sécurité et la disponibilité des données de l’entreprise.
          - Eventuellement intervenir sur les aspects télécom.
        featuredLink:
          enable: true
          name: "Lien fiche formation"
          url: "https://www.cesi.fr/formation/technicien-ne-systemes-et-reseaux-en-alternance-2169014/"

      - title: "Bac Sciences et Technique de l'Industrie et du Dévelopement Durable spécialisation Système Informatique et Numérique"
        school:
          name: "Lycée Blaise Pascal, Rouen"
          url: "https://pascal.lycee.ac-normandie.fr/"
        featuredLink:
          enable: true
          name: "Lien fiche formation"
          url: "https://etudiant.lefigaro.fr/vos-etudes/etudes-secondaires/33902-bac-sti2d-option-sin-tout-savoir/"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hugo Portfolio
        content: Mon portfolio en ligne, utilisant le générateur de site web static HUGO et le pipeline de déploiement Netlify.
        image: /images/projects/profile.png
        featured:
          name: Site
          link: https://yaelgrosjean.com/
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/YaelGj/portfolio

      - title: Application Gestion des arrêts de travails.
        content: Une double application mobile et web pour que les agents puissent déclarer leurs arrêts et les gestionnaires RH puissent assurer leurs suivis.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "PowerApps"
          - "Dataverse"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

      - title: Application Gestion des contrats d'alternances.
        content: Une application web pour que les gestionnaires puissent assurer le bon respect et suivie du processus de recrutement des futurs alternants SNCF.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "PowerApps"
          - "Dataverse"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2     

      - title: Jeux mobile android.
        content: Un jeux mobile inspiré des "beat them all" 2D des années 90.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Unity"
          - "C#"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2                  

      - title: Drone d'exploration et de prélèvement terrestre.
        content: Projet pour le Bac, 18/20 et félicitaions du jury.
        image: /images/projects/profile2.jpg
        featured:
          name: Vidéo
          link: https://drive.google.com/file/d/0B-PUugYpxnWzMXhVWDAwQTkxRG8/view?usp=drive_link&resourcekey=0-BJNtOZl3SIqkmrSxhfxU-A
        badges:
          - "React"
          - "React Native"
          - "JavaScript"
          - "HTML"
          - "CSS"
        links:
          - icon: fab fa-github
            url: https://github.com/YaelGj/RPI-HelpO     

      - title: Drone d'exploration et de prélèvement terrestre.
        content: Projet pour le Bac, 18/20 et félicitaions du jury.
        image: /images/projects/profile2.jpg
        featured:
          name: Vidéo
          link: https://drive.google.com/file/d/0B-PUugYpxnWzMXhVWDAwQTkxRG8/view?usp=drive_link&resourcekey=0-BJNtOZl3SIqkmrSxhfxU-A
        badges:
          - "Arduino"
          - "C++"
        links:
          - icon: fab fa-github
            url: https://github.com/YaelGj/ProjetDroneBac             

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Ma boîte de réception est toujours ouverte. Que vous ayez un projet à me proposer ou que vous souhaitiez simplement me saluer, je ferai de mon mieux pour vous répondre !
    email: yael.grosjean@protonmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/YaelGj
      linkedin: https://www.linkedin.com/in/yael-grosjean/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "2 Jan, 2006"
    articleList: "2 Jan, 2006"
    articleRecent: "2 Jan, 2006"
